---
apiVersion: v1
kind: Namespace
metadata:
  name: vs-prod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests
  namespace: vs-prod
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: vs-prod-pg-cluster
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests
  namespace: vs-prod-pg-cluster
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
