---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  generation: 1
  name: cnpg-immich-db
  namespace: pg-cluster
spec:
  cluster:
    name: pg-cluster-01
  name: immich-db
  owner: immich-user
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-init-sql
  namespace: pg-cluster
data:
  init.sql: |
    CREATE EXTENSION vchord CASCADE;
    CREATE EXTENSION earthdistance CASCADE;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-immich-db
  namespace: pg-cluster
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:16
        env:
        - name: PGHOST
          value: pg-cluster-01-rw.pg-cluster.svc.cluster.local
        - name: PGDATABASE
          value: immich-db
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: pg-cluster-01-superuser
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-cluster-01-superuser
              key: password
        command:
        - bash
        - -c
        - |
          until psql -c '\l' | grep immich-db; do sleep 2; done
          psql -f /scripts/init.sql
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: immich-init-sql
      restartPolicy: OnFailure  
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Cluster
# metadata:
#   name: immich-database
#   namespace: immich
# spec:
#   instances: 1
#   storage:
#     size: 10Gi
#   imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
#   postgresql:
#     shared_preload_libraries:
#       - "vchord.so"
#   bootstrap:
#     initdb:
#       # TODO: Use managed extensions (pg 18)
#       database: immich-db
#       owner: immich-user
#       secret:
#         name: immich-user-secret
#       postInitApplicationSQL:
#         # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
#         - CREATE EXTENSION vchord CASCADE;
#         - CREATE EXTENSION earthdistance CASCADE;
#         #   bootstrap:

# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Cluster
# metadata:
#   name: immich-database
#   namespace: immich
# spec:
#   instances: 1
#   storage:
#     size: 10Gi
#   imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
#   postgresql:
#     shared_preload_libraries:
#       - "vchord.so"
#   bootstrap:
#     initdb:
#       # TODO: Use managed extensions (pg 18)
#       database: immich-db
#       owner: immich-user
#       secret:
#         name: immich-user-secret
#       postInitApplicationSQL:
#         # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
#         - CREATE EXTENSION vchord CASCADE;
#         - CREATE EXTENSION earthdistance CASCADE;
#         #   bootstrap:
