---  
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  type: oci
  interval: 10m
  url: oci://ghcr.io/immich-app/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich
      version: "0.10.0"  # Setzen Sie hier die gewünschte Version
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: immich-values
