---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-init-sql
  namespace: pg-cluster
data:
  init.sql: |
    CREATE EXTENSION vchord CASCADE;
    CREATE EXTENSION earthdistance CASCADE;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-immich-db
  namespace: pg-cluster
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:16
        env:
        - name: PGHOST
          value: pg-cluster-01-rw.pg-cluster.svc.cluster.local
        - name: PGDATABASE
          value: immich-db
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: pg-cluster-01-superuser
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-cluster-01-superuser
              key: password
        command:
        - bash
        - -c
        - |
          until psql -c '\l' | grep immich-db; do sleep 2; done
          psql -f /scripts/init.sql
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: immich-init-sql
      restartPolicy: OnFailure
---  
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  type: oci
  interval: 10m
  url: oci://ghcr.io/immich-app/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich
      version: "0.10.0"  # Setzen Sie hier die gewünschte Version
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: immich-values
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
        - |-
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: immich-server
            namespace: immich
          spec:
            template:
              spec:
                volumes:
                  - name: truenas-media
                    persistentVolumeClaim:
                      claimName: immich-external-media-nfs-pvc
                containers:
                  - name: main
                    volumeMounts:
                      - name: truenas-media
                        mountPath: /data/external-media