---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-claim
  namespace: immich
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: valkey-claim
  namespace: immich
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-ml-claim
  namespace: immich
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: immich-external-media-nfs-pv
# spec:
#   capacity:
#     storage: 100Gi
#   accessModes:
#     - ReadOnlyMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs
#   mountOptions:
#     - hard
#     - nfsvers=4.1
#     - rsize=1048576
#     - wsize=1048576
#     - timeo=600
#     - retrans=2
#     - async              # ← DAS IST DER WICHTIGE TEIL!
#     - noatime
#     - nodiratime
#   nfs:
#     path: /mnt/SpinningData/NatiaBilder/
#     server: 192.168.2.109
# ---
# # PersistentVolumeClaim
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-external-media-nfs-pvc
#   namespace: immich
# spec:
#   accessModes:
#     - ReadOnlyMany
#   volumeName: immich-external-media-nfs-pv
#   storageClassName: nfs
#   resources:
#     requests:
#       storage: 100Gi