---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: flux-system
spec:
  targetNamespace: elastic-system
  chart:
    spec:
      chart: eck-operator
      interval: 5m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: elastic-operator
      version: 2.16.1
  install:
    remediation:
      retries: 3
  interval: 10m
  releaseName: elastic-operator
  test:
    enable: false
  timeout: 5m
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: karpenter.sh/nodepool
    #               operator: DoesNotExist
    #     podAntiAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #         - labelSelector:
    #             matchLabels:
    #               app.kubernetes.io/instance: elastic-operator
    #               app.kubernetes.io/name: elastic-operator
    #           topologyKey: kubernetes.io/hostname
