---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/external-dns/
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: hetzner-credentials
  namespace: external-dns
spec:
  itemPath: "vaults/Infrastruktur/items/hetzner-dns-token"
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: external-dns
#   namespace: external-dns
# spec:
#   interval: 10m
#   chart:
#     spec:
#       chart: external-dns
#       version: 1.18.0
#       sourceRef:
#         kind: HelmRepository
#         name: external-dns
#         namespace: flux-system
#   valuesFrom:
#     - kind: ConfigMap
#       name: external-dns-values
