apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns-stack
resources:
  - external-dns.yaml
  - dns-test.yaml
configMapGenerator:
  - name: external-dns-values
    namespace: external-dns
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true

