namespace: external-dns
policy: sync
provider:
  name: webhook
  webhook:
    image:
      repository: docker.io/hetznercloud/external-dns-hetzner-webhook
      tag: v0.1.2 # x-releaser-pleaser-version
    env:
      - name: HETZNER_TOKEN
        valueFrom:
          secretKeyRef:
            name: hetzner-credentials
            key: api-key
extraArgs:
  - "--txt-prefix=reg-%{record_type}-"