---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pg-nextcloud-secret
spec:
  itemPath: "vaults/VS-Infra/items/Nextcloud Datenbank"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-nextcloud-admin
spec:
  itemPath: "vaults/VS-Infra/items/VS Nextcloud Admin"