---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pg-nextcloud-secret
spec:
  itemPath: "vaults/DT-Infra/items/Nextcloud Datenbank"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dt-nextcloud-admin
spec:
  itemPath: "vaults/DT-Infra/items/ER Nextcloud Admin"
# ---
# apiVersion: onepassword.com/v1
# kind: OnePasswordItem
# metadata:
#   name: vs-document-test-smb
# spec:
#   itemPath: "vaults/VS-Infra/items/VS-Document-Test-SMB"
# ---
# apiVersion: onepassword.com/v1
# kind: OnePasswordItem
# metadata:
#   name: vs-nextcloud-s3
# spec:
#   itemPath: "vaults/VS-Infra/items/VS Nextcloud S3"