apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak
resources:
  - ../../base/security/keycloak

patches:
  - target:
      kind: StatefulSet
      name: keycloak
    patch: |-
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: theme-cvo-login
            configMap:
              name: kc-theme-cvo-login
          - name: theme-cvo-messages
            configMap:
              name: kc-theme-cvo-messages
          - name: theme-cvo-css
            configMap:
              name: kc-theme-cvo-css
          - name: theme-cvo-img
            configMap:
              name: kc-theme-cvo-img
          - name: theme-cvo-email
            configMap:
              name: kc-theme-cvo-email
          - name: theme-cvo-email-html
            configMap:
              name: kc-theme-cvo-email-html
          - name: theme-cvo-email-text
            configMap:
              name: kc-theme-cvo-email-text
          - name: theme-cvo-email-messages
            configMap:
              name: kc-theme-cvo-email-messages
  - target:
      kind: StatefulSet
      name: keycloak
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: theme-cvo-login
            mountPath: /opt/keycloak/themes/cvo/login
            readOnly: true
          - name: theme-cvo-messages
            mountPath: /opt/keycloak/themes/cvo/login/messages
            readOnly: true
          - name: theme-cvo-css
            mountPath: /opt/keycloak/themes/cvo/login/resources/css
            readOnly: true
          - name: theme-cvo-img
            mountPath: /opt/keycloak/themes/cvo/login/resources/img
            readOnly: true
          - name: theme-cvo-email
            mountPath: /opt/keycloak/themes/cvo/email
            readOnly: true
          - name: theme-cvo-email-html
            mountPath: /opt/keycloak/themes/cvo/email/html
            readOnly: true
          - name: theme-cvo-email-text
            mountPath: /opt/keycloak/themes/cvo/email/text
            readOnly: true
          - name: theme-cvo-email-messages
            mountPath: /opt/keycloak/themes/cvo/email/messages
            readOnly: true
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/keycloak/keycloak:26.7.2
