---
apiVersion: v1
kind: Namespace
metadata:
  name: iam
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests
  namespace: iam
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: iam
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: iam
  path: ./base/security/keycloak
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      DOMAIN: iam.vanille.hamburg
      INGRESS: traefik
      CLUSTER_ISSUER: letsencrypt-prod
      DATABASE_SECRET_ID: "vaults/VS-Infra/items/KeyCloak Database User"
      ADMIN_SECRET_ID: "vaults/VS-Infra/items/KeyCloak Admin"