apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/security/cert-manager
  - ../base/networking/dns-manager
  - ../base/monitoring/prometheus-stack
  - ../base/operator/cnpg
  - pg-cluster-01.yaml
  - vanille-shop-test.yaml
patches:
  - target:
      kind: OnePasswordItem
      name: hetzner-credentials
      namespace: external-dns
    patch: |-
      - op: replace
        path: /spec/itemPath
        value: "vaults/VS-Infra/items/hetzner-api-key"
  - target: 
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: add
        path: /spec/values
        value:
          grafana:
            ingress:
              enabled: true
              ingressClassName: traefik 
              annotations: 
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              labels: {}
              hosts: 
                - grafana.vanille.hamburg
              path: /
              tls: 
                - secretName: grafana-general-tls
                  hosts:
                    - grafana.vanille.hamburg
