apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/networking/dns-manager
  - ../base/monitoring/prometheus-stack
  - vanille-shop-test.yaml
patches:
  - target:
      kind: OnePasswordItem
      name: hetzner-credentials
      namespace: external-dns
    patch: |-
      - op: replace
        path: /spec/itemPath
        value: "vaults/VS-Infra/items/hetzner-api-key"
  - target: 
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: add
        path: /spec/values
        value:
          hosts:
            - grafana.vanille.hamburg
