---
apiVersion: v1
kind: Namespace
metadata:
  name: pg-cluster
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pg-backup-s3-key-secret
  namespace: pg-cluster
spec:
  itemPath: "vaults/VS-Infra/items/PG Backup S3 Secrets"
--- # Wawi VS Test - 
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pg-superuser-secret
  namespace: pg-cluster
spec:
  itemPath: "vaults/VS-Infra/items/VS Postgres Superuser"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pg-keycloak-secret
  namespace: pg-cluster
spec:
  itemPath: "vaults/VS-Infra/items/KeyCloak Database User"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pg-wawi-secret
  namespace: pg-cluster
spec:
  itemPath: "vaults/VS-Infra/items/Wawi VS Test"
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: hetzner-s3-store
  namespace: pg-cluster
spec:
  configuration:  
    destinationPath: s3://wh-gmbh-pg-backup/20260311-2
    endpointURL: https://fsn1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: pg-backup-s3-key-secret
        key: AccessKey
      secretAccessKey:
        name: pg-backup-s3-key-secret
        key: SecretKey
    wal:
      compression: gzip
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: hetzner-s3-restore
  namespace: pg-cluster
spec:
  configuration:
    destinationPath: s3://wh-gmbh-pg-backup/20260311-1
    endpointURL: https://fsn1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: pg-backup-s3-key-secret
        key: AccessKey
      secretAccessKey:
        name: pg-backup-s3-key-secret
        key: SecretKey
    wal:
      compression: gzip
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pg-cluster
  namespace: flux-system
spec:
  targetNamespace: pg-cluster
  interval: 10m0s
  path: ./base/pg-clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |-
        - op: replace
          path: /spec/plugins
          value:
            - name: barman-cloud.cloudnative-pg.io
              isWALArchiver: true
              parameters:
                barmanObjectName: hetzner-s3-store
        - op: replace
          path: /spec/managed
          value:
            roles:
              - name: wawi
                login: true
                ensure: present
                createdb: false
                passwordSecret:
                  name: pg-wawi-secret
              - name: keycloak
                login: true
                ensure: present
                createdb: false
                passwordSecret:
                  name: pg-keycloak-secret
        - op: add
          path: /spec/externalClusters
          value:
            - name: restore-source
              plugin:
                name: barman-cloud.cloudnative-pg.io
                parameters:
                  barmanObjectName: hetzner-s3-restore
                  serverName: pg-cluster-01  
        - op: add
          path: /spec/bootstrap
          value:
            recovery:
              source: restore-source
      target:
        kind: Cluster
        name: pg-cluster-01
        namespace: pg-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: wawi-database
  namespace: pg-cluster
spec:
  name: wawi
  owner: wawi
  cluster:
    name: pg-cluster-01
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak-database
  namespace: pg-cluster
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: pg-cluster-01

# - op: replace
#   path: /spec/managed
#   value:
#     roles:
#       - name: immich-user
#         login: true
#         ensure: present
#         createdb: false
#         passwordSecret:
#           name: immich-user-secret
#       - name: schwarze-null-user
#         login: true
#         ensure: present
#         createdb: false
#         passwordSecret:
#           name: schwarze-null-user-secret
#       - name: vs-user
#         login: true
#         ensure: present
#         createdb: false
#         passwordSecret:
#           name: vs-user-secret
  