---
apiVersion: v1
kind: Namespace
metadata:
  name: smb-csi-driver
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests
  namespace: smb-csi-driver
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smb-csi-driver
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: smb-csi-driver
  path: ./base/storage/smb-csi-driver
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      SMB_VOLUME_URL: //u566750.your-storagebox.de/u566750-sub1
      SMB_CSI_DRIVER_CREDS_ITEM_PATH: vaults/VS-Infra/items/VS-Document-Test-SMB
      NAMESPACE: smb-csi-driver
      STORAGE_CLASS_NAME: storagebox-test-smb-sc
