---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vs-wawi-prod-application
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./base/application-space
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      APPLICATION_NAMESPACE: vanille-shop-prod
      APPLICATION: vanille-shop-prod
      KUSTOMIZATION_PATH: ./environments/vanille-shop-production