apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - pricing-configmap.yaml
  # - open-cost.yaml
  - CURRENT/rbac.yaml
  - CURRENT/service-account.yaml
  - CURRENT/service-monitor.yaml
  - CURRENT/configmaps.yaml
  - CURRENT/deployment.yaml
  - CURRENT/service.yaml
