apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-model
  namespace: opencost
data:
  default.json: |
    {
      "provider": "custom",
      "description": "Hetzner on-prem pricing",
      "CPU": "0.001763",
      "spotCPU": "0.001763",
      "RAM": "0.000441",
      "spotRAM": "0.000441",
      "GPU": "0",
      "storage": "0.0000932",
      "zoneNetworkEgress": "0",
      "regionNetworkEgress": "0",
      "internetNetworkEgress": "0"
    }
