apiVersion: v1
kind: Service
metadata:
  name: open-cost-opencost
  namespace: open-cost
  labels:
    app.kubernetes.io/instance: open-cost  
    app.kubernetes.io/name: opencost       
spec:
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9003
    protocol: TCP
    targetPort: 9003
  - name: http-ui
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: open-cost
    app.kubernetes.io/name: opencost
  sessionAffinity: None
  type: ClusterIP
