apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - external-dns
  - monitoring
  - operators.yaml
  - pg-cluster-01.yaml
  - open-cost.yaml
#  - iam.yaml
#  - elternrat.yaml
