apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - git-repo.yaml
  - cert-manager.yaml
  - external-dns.yaml
  - monitoring.yaml
#  - ../base/operator/cnpg
#  - pg-cluster-01.yaml
#  - iam.yaml
#  - nextcloud.yaml
#  - vanille-shop-test.yaml
#   - target:
#       kind: StorageClass
#       name: storagebox-test-smb-sc
#       namespace: kube-system
#     patch: |-
#       - op: replace
#         path: /parameters/source
#         value: "//u566750.your-storagebox.de/u566750-sub1"
