  # - target:
  #     kind: HelmRelease
  #     name: grafana
  #     namespace: monitoring
  #   patch: |-
  #     - op: add
  #       path: /spec/values
  #       value: 
  #         grafana:
  #           ingress:
  #             hosts:        
  #               - "grafana.vanille.hamburg"
  #           persistence:
  #             enabled: true
  #             storageClassName: hcloud-volumes
  #         prometheus:
  #           prometheusSpec:
  #             storageSpec:
  #               volumeClaimTemplate:
  #                 spec:
  #                   storageClassName: hcloud-volumes