apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vanille-shop-wawi-test
  namespace: ${FLUX_NAMESPACE}
spec:
  interval: 10m0s
  targetNamespace: ${TARGET_NAMESPACE}
  path: ./applications/vanille-shop-wawi
  prune: true
  sourceRef:
    kind: GitRepository
    name: datentraum-platform-fluxcd
  postBuild:
    substitute:
      QUOTING: '"'
      VS_ENVIRONMENT: "test"
      TARGET_NAMESPACE: "vanille-shop-test"
      FLUX_NAMESPACE: "vanille-shop-flux"
      STORAGE_CLASS_NAME: "storagebox-test-smb-sc"
      PVC_STORAGE_SIZE: "10Gi"
      SHOP_WARE_API_URL: "https://www.vanille-shop.de/stageware1/api/"
      SHOP_WARE_API_AUTHORIZATION_URL: "https://www.vanille-shop.de/stageware1/api/oauth/token"
      SHOW_WARE_INTEGRATION_ENABLED: "false"
      LOGGING_LEVEL_ROOT: "INFO"
      WAWI_DB_SECRET: "vaults/VS-Infra/items/Wawi VS Test"  
      WAWI_SHOPWARE_SECRET: "vaults/VS-Infra/items/Showpare VS API Key TEST"
      WAWI_SMTP_SECRET: "vaults/VS-Infra/items/VS Mail SMTP"
      WAWI_MQTT_SECRET: "vaults/VS-Infra/items/VS Mqtt Client"