apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus-stack
resources:
  - prometheus-helm.yaml
configMapGenerator:
  - name: prometheus-values
    namespace: monitoring
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true

