---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datentraum-collabora
  namespace: datentraum
spec:
  interval: 10m0s
  targetNamespace: ${TARGET_NAMESPACE}
  path: ./applications/collabora
  prune: true
  sourceRef:
    kind: GitRepository
    name: datentraum-platform-fluxcd
  postBuild:
    substitute:
      TARGET_NAMESPACE: datentraum
      TLS_SECRET_NAME: collabora-nextcloud-general-tls
      DOMAIN: code.datentraum.de
      CLUSTER_ISSUER: letsencrypt-prod
      