apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubescape.yaml
configMapGenerator:
  - name: kubescape-values
    namespace: kubescape
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
