---
apiVersion: v1
kind: Namespace
metadata:
  name: cvo-elternrat-cloud
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests
  namespace: cvo-elternrat-cloud
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
