---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: elternrat-flux-admin-sa
  namespace: cvo-elternrat-cloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: cvo-elternrat-cloud-admin
  namespace: cvo-elternrat-cloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: cvo-elternrat-cloud-admins
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: elternrat-flux-admin-sa
  namespace: cvo-elternrat-cloud