---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-db-secret
spec:
  itemPath: ${QUOTING}${WAWI_DB_SECRET}${QUOTING}  
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-shopware-secret
spec:
  itemPath: ${QUOTING}${WAWI_SHOPWARE_SECRET}${QUOTING}  
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-smtp-secret
spec:
  itemPath: ${QUOTING}${WAWI_SMTP_SECRET}${QUOTING}  
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-mqtt-secret
spec:
  itemPath: ${QUOTING}${WAWI_MQTT_SECRET}${QUOTING}  
---
apiVersion: v1
kind: Secret
metadata:
  name: private-docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuaGFjaG1hbm4uaGFtYnVyZyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJncGQ0cGVkNGF1ZjBQQU5AaGF4IiwiYXV0aCI6IllXUnRhVzQ2WjNCa05IQmxaRFJoZFdZd1VFRk9RR2hoZUE9PSJ9fX0=

  