---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-db-secret
spec:
  itemPath: "vaults/VS-Infra/items/Wawi VS Test"  
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-shopware-secret
spec:
  itemPath: "vaults/VS-Infra/items/Showpare VS API Key"  
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-smtp-secret
spec:
  itemPath: "vaults/VS-Infra/items/VS Mail SMTP"  
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-mqtt-secret
spec:
  itemPath: "vaults/VS-Infra/items/VS Mqtt Client"  
---
apiVersion: v1
kind: Secret
metadata:
  name: private-docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuaGFjaG1hbm4uaGFtYnVyZyI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJncGQ0cGVkNGF1ZjBQQU5AaGF4IiwiYXV0aCI6IllXUnRhVzQ2WjNCa05IQmxaRFJoZFdZd1VFRk9RR2hoZUE9PSJ9fX0=

  