---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vs-document-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ${STORAGE_CLASS_NAME}