apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/monitoring/prometheus-stack
  - one-password-secrets.yaml
patches:
  - target:
      kind: OnePasswordItem
      name: grafana-admin-credentials
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec/itemPath
        value: "vaults/DT-Infra/items/Grafana Admin"
  - target: 
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: add
        path: /spec/values
        value:
          grafana:
            operator:
              dashboardsConfigMapRefEnabled: false
            admin:
              ## Name of the secret. Can be templated.
              existingSecret: "grafana-admin-credentials"
              userKey: username
              passwordKey: password
            ingress:
              enabled: true
              ingressClassName: traefik 
              annotations: 
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
              labels: {}
              hosts: 
                - grafana.datentraum.de
              path: /
              tls: 
                - secretName: grafana-general-tls
                  hosts:
                    - grafana.datentraum.de
