---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: storagebox-test-smb-creds
  namespace: ${NAMESPACE}
spec:
  itemPath: "${SMB_CSI_DRIVER_CREDS_ITEM_PATH}"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storagebox-test-smb-sc
provisioner: smb.csi.k8s.io
parameters:
  # See https://github.com/kubernetes-csi/csi-driver-smb/blob/master/docs/driver-parameters.md
  # On Windows, "*.default.svc.cluster.local" could not be recognized by csi-proxy
  source: //u566750.your-storagebox.de/u566750-sub1
  # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  # with PV name under source
  subDir: $${pvc.metadata.namespace}/$${pvc.metadata.name}
  csi.storage.k8s.io/provisioner-secret-name: storagebox-test-smb-creds
  csi.storage.k8s.io/provisioner-secret-namespace: ${NAMESPACE}
  csi.storage.k8s.io/node-stage-secret-name: storagebox-test-smb-creds
  csi.storage.k8s.io/node-stage-secret-namespace: ${NAMESPACE}
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
---