---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-document-test-smb
  namespace: default
spec:
  itemPath: "vaults/VS-Infra/items/VS Document Test SMB"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-smb
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: smb-server.default.svc.cluster.local/share##
    volumeAttributes:
      source: //u566750-sub1.your-storagebox.de/u566750-sub1
    nodeStageSecretRef:
      name: vs-document-test-smb
      namespace: default
---
# Deployment of a simple test pod to verify the functionality of the smb-csi-driver
apiVersion: v1
kind: Pod
metadata:
  name: smb-test-pod
  namespace: default
spec:
  containers:
    - name: smb-test-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: smb-test-volume
          mountPath: /mnt/smb
  volumes:
    - name: smb-test-volume
      persistentVolumeClaim:
        claimName: smb-test-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb 