---
apiVersion: v1
kind: Namespace
metadata:
  name: pg-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster 
metadata:
  name: cluster-example-initdb
  namespace: pg-cluster
spec:
  instances: 3
  bootstrap:
    initdb:
      database: initialdb
      owner: initialUser
      secret:
        name: initial-user-secret
  storage:
    size: 10Gi