---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  targetNamespace: immich
  interval: 10m0s
  path: ./hetzner-k8s-01/applications/immich
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
