---
apiVersion: v1
kind: Namespace
metadata:
  name: vanille-shop-production
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  generation: 1
  name: cnpg-vs-db
  namespace: pg-cluster
spec:
  cluster:
    name: pg-cluster-01
  name: vs-db
  owner: vs-user
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vs-wawi
  namespace: flux-system
spec:
  targetNamespace: vanille-shop-production
  interval: 10m0s
  path: ./hetzner-k8s-vs-01/applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
