---
apiVersion: v1
kind: Service
metadata:
  name: pg-cluster-01-rw-np
  namespace: pg-cluster
  labels:
    cnpg.io/cluster: pg-cluster-01
  annotations:
    cnpg.io/operatorVersion: 1.27.0
spec:
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30433
  selector:
    cnpg.io/cluster: pg-cluster-01
    cnpg.io/instanceRole: primary
  type: NodePort