---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pg-backup-s3-key-secret
  namespace: vs-prod-pg-cluster
spec:
  itemPath: "vaults/VS-Infra/items/PG Backup S3 Secrets"
--- # Wawi VS Test - 
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-prod-pg-superuser-secret
  namespace: vs-prod-pg-cluster
spec:
  itemPath: "vaults/VS-Infra/items/VS Postgres Superuser PROD"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: vs-prod-pg-wawi-secret
  namespace: vs-prod-pg-cluster
spec:
  itemPath: "vaults/VS-Infra/items/Wawi VS PROD"