---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: datentraum-flux-sa
  namespace: datentraum
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: deploymnent-manager
  namespace: datentraum
rules:
- apiGroups:
  - onepassword.com
  resources:
  - onepassworditems
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: deploymnent-manager-binding
  namespace: datentraum
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploymnent-manager
subjects:
- kind: ServiceAccount
  name: datentraum-flux-sa
  namespace: datentraum