---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ${APPLICATION}-deploy-ssh-key
  namespace: ${APPLICATION_NAMESPACE}-flux
spec:
  itemPath: "vaults/VS-Infra/items/VS GitHub Deploy SSH-Key"  
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ${APPLICATION_NAMESPACE}-platform-fluxcd
  namespace: ${APPLICATION_NAMESPACE}-flux
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: ${APPLICATION}-deploy-ssh-key
  url: ssh://git@github.com/ahachmann/datentraum-platform-fluxcd.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${APPLICATION}-fluxcd
  namespace: ${APPLICATION_NAMESPACE}-flux
spec:
  serviceAccountName: ${APPLICATION}-flux-sa
  interval: 10m0s
  path: ${KUSTOMIZATION_PATH}
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${APPLICATION_NAMESPACE}-platform-fluxcd
  postBuild:
    substitute:
      FLUX_NAMESPACE: ${APPLICATION_NAMESPACE}-flux
      TARGET_NAMESPACE: ${APPLICATION_NAMESPACE}
      GIT_REPOSITORY: ${APPLICATION_NAMESPACE}-platform-fluxcd