---
apiVersion: v1
kind: Namespace
metadata:
  name: arc-runners
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests
  namespace: arc-runners
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"  